# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hvq64IswvRP8tpFSFurt14IizNCvTVJC
"""

import pandas as pd
import numpy as np
#التحدي 1
df = pd.DataFrame({
    "age": [25, "unknown", 30, "NA", 40],
    "salary": ["5000", "N/A", "?", "7000", "not reported"],
    "city": ["Riyadh", "Jeddah", "unknown", "Dammam", "Riyadh"]
})
missing_tokens = ["N/A", "NA", "not reported", "unknown", "?"]
df.replace(missing_tokens, np.nan, inplace=True)

print("Data after cleaning:")
print(df)
missing_percentage = (df.isna().mean() * 100).round(1)

print("\nMissing value percentage per column:")
print(missing_percentage)